import org.code.neighborhood.*;


/**
 * The NeighborhoodRunner class runs the entire program to plant
 * a backgroound and the Stanford S using the MuralPainter and StanfordPainter classes.
  */

public class NeighborhoodRunner {
  public static void main(String[] args) {

  // Create an instance of MuralPainter to paint the white background
  MuralPainter backgroundPainter = new MuralPainter();
    backgroundPainter.paintBackground("white", 16); //Paints the background

    // Create an instance of StanfordPainter to paint the red S and green tree
    StanfordPainter stanford = new StanfordPainter();    
    stanford.paintStanford("darkRed"); //Paints the red S and green tree


    // Paints the Red S and Green Tree
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 6);
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 6);
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 2);
    stanford.turnRight();
    stanford.paintLine("darkRed", 3);
    stanford.turnRight();
    stanford.paintLine("darkRed", 1);
    stanford.turnLeft();
    stanford.paintLine("darkRed", 3);
    stanford.turnLeft();
    stanford.paintLine("darkRed", 3);
    stanford.turnLeft();
    stanford.paintLine("darkRed", 5);
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 3);
    stanford.turnRight();
    stanford.move();
    stanford.paintLine("darkRed", 7);
    stanford.turnRight();
    stanford.paintLine("darkRed", 1);
    stanford.turnRight();
    stanford.paintLine("darkRed", 2);
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 7);
    stanford.turnRight();
    stanford.paintLine("darkRed", 8);
    stanford.turnRight();
    stanford.paintLine("darkRed", 2);
    stanford.turnRight();
    stanford.paintLine("darkRed", 3);
    stanford.turnRight();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.paintLine("darkRed", 6);
    stanford.turnLeft();
    stanford.paintLine("darkRed", 6);
    stanford.turnLeft();
    stanford.paintLine("darkRed", 6);
    stanford.turnRight();
    stanford.paintLine("darkRed", 3);
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.paintLine("darkRed", 7);
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.paintLine("darkRed", 6);
    stanford.turnRight();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.paintLine("white", 16);
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 4);
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.paintLine("darkRed", 6);
    stanford.turnLeft();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.paintLine("darkRed", 3);
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnRight();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("white", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.paintLine("green", 14);
    stanford.turnRight();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.turnRight();
    stanford.move();
    stanford.turnRight();
    stanford.move();
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.move();
    stanford.paintLine("green", 1);
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    stanford.turnLeft();
    stanford.turnLeft();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.move();
    stanford.paintLine("darkRed", 1);
    
    
    
    
    
 
    
    
    
    
    
    
  }
}